spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/okinawadb
    username: root
    password: '{cipher}AQAfw0F18gAVBKgYDq/7FIrtXGctHF2uryWfEi4gZEyX+SsHh0lnhQK/WHWc7RdXrl06cFGUyzMUk8KADdDa65zzcHyDDmOzQlFCJf+dnrfmL8holjtXEGBptLlmnMl5CovsCgnkkbKHiMyVkYYzu8UYprS+FQzVG18qb+V1nWfdVL2q2eS9y0tOaa1CWXfliGKHnAnw4VAKcjDKvbVriYqAugOd0ZcBH7Lt/oAeShh014lpxSz+dkUiGNSRMkdMHnyJ0CBPZgHgOHPZYe84isw/nCqy+zYUgpDF4QVa7mUK+GfdF7HMHG1ehJFNkBhpggTtbwh3zq98JVYsRv2/Lw9i5Wow+ON5vCwUZCju/JC0zWCwLhl3FbFXvKMoY5SvJX4='



token:
  expiration_time: 8640000000
  secret: '{cipher}AQBDnz0ukjz2e4AyVlJBBgN8XKl6SAJfNxCh0rahxMdtYyLLdR1C1ncXwkZFzmSrEKxXrPqQmxt90JULrXf7wlVI2+r5SEfoXSFDEu2u4mtOzDHqCNskksomJ7SoW5+XC7r/pu4wOArKf4SJyLxlzV0zmka6flKRtbnH6ModL4x32x3QkUW1OakIr0V25jpltgB7pGFb65xEw8AmREuq/KngcFBwKCx9NaeIxGtITLwTl8MnfTbd6RirMnreklaa+ULtbCVJg2t8DzRNQt0guXnZtGuE0earDvGakP3DA9ftjNreYL+duOlLMZoGnTJDVW2Y8tXN9HPSvOaDiDcTXO5Cp1cTfrBe0nr6GbiajSTlSHjellqGQx5m6E4A9APwwlY='

gateway:
  ip: 127.0.0.1

